pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Testing1
    displayName: 'Test the Component'
    steps:
      - checkout: self
      - script: |
          cat pipelines/chat-notify.yml
        workingDirectory: alert-test
  - job: ChatAlerts
    displayName: 'Send Google Chat Alert'
    dependsOn:
      - Testing1
    condition: failed()
    steps:
      - template: templates/notify-template.yaml
        parameters:
          webhook_url: "https://chat.googleapis.com/v1/spaces/AAAA-y5RxXY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=n678xyeVxt1ZXmw052hT_4pgJIm1BNSNE-iYDf0AgZY%3D"
