pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Testing1
    displayName: 'Test component'
    steps:
      - checkout: self
      - script: |
          cat pipelines/chat-notify.yml
        workingDirectory: alert-test
  - job: SendingAlert
    displayName: Sending alert
    dependsOn:
      - Testing1
    condition: eq(dependencies.Testing1.result, 'Failed')
    steps:
      - template: 'templates/notify-template.yaml'
        parameters:
          PIPELINE_NAME: 'alert-test'
          ENVIRONMENT: "prod"
          PIPELINE_STATUS: "Failed"
          GOOGLE_CHAT_SPACE: "AAAA-y5RxXY"
          GOOGLE_CHAT_KEY: "AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI"
          GOOGLE_CHAT_TOKEN: "n678xyeVxt1ZXmw052hT_4pgJIm1BNSNE-iYDf0AgZY%3D"
